---

- name: Bootstrap all Hosts
  hosts: dns
  become: true
  gather_facts: false
  roles:
    - role: robertdebock.bootstrap

- name: dnsmaq installation and configuration
  hosts: dns
  become: true
  gather_facts: true
  roles:
    - role: robertdebock.dnsmasq

- name: Cleanup Apache on proxy
  hosts: dns
  become: true
  gather_facts: true
  tasks:
    - name: Remove other webservers
      ansible.builtin.apt:
        state: absent
        update_cache: true
        pkg:
          - apache2
          - php

- name: Caddy Web-Proxy
  hosts: dns
  become: true
  gather_facts: true
  roles:
    - role: maxhoesel.caddy.caddy_server
      caddy_config_mode: Caddyfile
      caddy_caddyfile: |
        {
          email caddy-homelab@ranta.ch
        }
        lukylab.duckdns.org,
        lab.ranta.ch {
          header Content-Type text/html
          respond <<HTML
            <html><head><title>LukyLAB</title></head>
            <body><h1>Luky LAB</h1></body>
            </html>
            HTML 200
        }
        # No route from inside the PVE-Container to the PVE-Host
        #lab.ranta.local {
        #  tls internal
        #  reverse_proxy https://192.168.88.5:8006 {
        #    header_down Strict-Transport-Security "max-age=31536000; includeSubdomains;"
        #    header_down Content-Security-Policy "default-src 'self' data: https: 'unsafe-inline'"
        #  }
        #}
        caddy.ranta.local {
          tls internal
          metrics /metrics
        }
        ansible.ranta.local {
          tls internal
          reverse_proxy http://192.168.88.6:3000 {
            header_down Strict-Transport-Security "max-age=31536000; includeSubdomains;"
            header_down Content-Security-Policy "default-src 'self' data: https: 'unsafe-inline'"
          }
        }
        cloud.ranta.ch,
        cloud.lab.ranta.ch {
          redir /.well-known/carddav /remote.php/dav 301
          redir /.well-known/caldav /remote.php/dav 301
          reverse_proxy http://192.168.88.10:80 {
            header_down Strict-Transport-Security "max-age=31536000; includeSubdomains;"
          }
        }

- name: Start Caddy
  hosts: dns
  become: true
  gather_facts: true
  tasks:
    - name: Cady trust to install cerificates
      ansible.builtin.shell: sudo HOME=~caddy caddy trust

    - name: Enable Caddy
      ansible.builtin.service:
        name: caddy.servive
        enabled: true
        state: started
