---

- name: Bootstrap all Hosts
  hosts: cloud
  become: true
  gather_facts: false
  roles:
    - role: robertdebock.bootstrap

- name: Prepare for Nextcloud
  hosts: cloud
  become: true
  gather_facts: false
  tasks:
    - name: Install Packages
      ansible.builtin.apt:
        state: latest
        update_cache: true
        pkg:
          - mariadb-server
          - apache2
          - imagemagick
          - graphviz
          - curl
          - php
          - php-apcu
          - php-curl
          - php-gd
          - php-imagick
          - php-fpm
          - php-cli
          - php-mbstring
          - php-xml
          - php-zip
          - php-intl
          - php-bz2
          - php-mysql
          - php-bcmath
          - php-gmp
          - ffmpeg

    - name: Configure Apache2 http2
      ansible.builtin.template:
        src: templates/cloud/http2.conf.j2
        dest: /etc/apache2/conf-available/http2.conf

    - name: Enable Apache2 Modules
      ansible.builtin.shell: |
        /usr/sbin/a2enmod http2
        /usr/sbin/a2enconf http2
        /usr/sbin/a2enmod env
        /usr/sbin/a2enmod rewrite
        /usr/sbin/a2enmod headers
        /usr/sbin/a2enmod dir
        /usr/sbin/a2enmod mime
        /usr/sbin/a2enmod ssl
        /usr/sbin/a2dismod webdav
        /bin/true

- name: Install and Configure Nextcloud
  hosts: cloud
  become: true
  gather_facts: false
  tasks:
    - name: Configure Apache2
      ansible.builtin.template:
        src: templates/cloud/cloud.conf.j2
        dest: /etc/apache2/sites-available/nextcloud.conf

    - name: Configure Systemd Nextcloud-Cron Service
      ansible.builtin.template:
        src: templates/cloud/nextcloud.service.j2
        dest: /lib/systemd/system/nextcloud.service
        mode: 0644
        owner: root
        group: root

    - name: Configure Systemd Nextcloud-Cron Timer
      ansible.builtin.template:
        src: templates/cloud/nextcloud.timer.j2
        dest: /lib/systemd/system/nextcloud.timer
        mode: 0644
        owner: root
        group: root

    - name: Enable Nextcloud-Cron Timer
      ansible.builtin.service:
        name: nextcloud.timer
        enabled: true
        state: started

    - name: Ensure Nextcloud Directory exists
      ansible.builtin.file:
        path: '{{ nextcloud_directory }}'
        state: directory
        mode: '0755'
        owner: 'www-data'
        group: 'www-data'

    - name: Ensure Nextcloud Data-Directory exists
      ansible.builtin.file:
        path: '{{ nextcloud_data_directory }}'
        state: directory
        mode: '0755'
        owner: 'www-data'
        group: 'www-data'

    - name: Enable Cloud in Apache2
      ansible.builtin.shell: /usr/sbin/a2ensite nextcloud.conf
      notify: Reload Apache2

  handlers:
    - name: Reload Apache2
      ansible.builtin.service:
        name: apache2
        state: reloaded

    - name: Restart Apache2
      ansible.builtin.service:
        name: apache2
        state: restarted
